services:
  app:
    container_name: the-pale
    image: ${DOCKERHUB_USERNAME}/the-pale:latest
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: '0.7'  # Match observed usage
    mem_limit: 512m
    mem_reservation: 256m
    restart: "no"  # Prevents auto-restart to see actual failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.depeche.rule=Host(`beta.buszewski.studio`)
      - traefik.http.routers.depeche.entrypoints=websecure
      - traefik.http.routers.depeche.tls=true
      - traefik.http.routers.depeche.tls.certresolver=letsencrypt
      - traefik.http.services.depeche.loadbalancer.server.port=3000

networks:
  traefik-public:
    name: traefik-public
