services:
  app:
    container_name: the-pale
    image: ghcr.io/${GITHUB_OWNER}/the-pale:latest
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.depeche.rule=Host(`beta.buszewski.studio`)
      - traefik.http.routers.depeche.entrypoints=websecure
      - traefik.http.routers.depeche.tls=true
      - traefik.http.routers.depeche.tls.certresolver=letsencrypt
      - traefik.http.services.depeche.loadbalancer.server.port=3000

networks:
  traefik-public:
    external: true
    name: traefik-public
