import alacrittyIcon from "./alacritty.png";
import astroIcon from "./astro.png";
import backlogIcon from "./backlog.png";
import bitbucketIcon from "./bitbucket.png";
import ccIcon from "./cc.png";
import cssIcon from "./css.png";
import designerIcon from "./designer.png";
import directusIcon from "./directus.png";
import dockerIcon from "./docker.png";
import figmaIcon from "./figma.png";
import fishIcon from "./fish.png";
import gitIcon from "./git.png";
import githubIcon from "./github.png";
import gitlabIcon from "./gitlab.png";
import hayIcon from "./hay.png";
import hay2Icon from "./hay2.png";
import htmlIcon from "./html.png";
import jestIcon from "./jest.png";
import jsIcon from "./js.png";
import netlifyIcon from "./netlify.png";
import nextIcon from "./next.png";
import notebookIcon from "./notebook.png";
import photoIcon from "./photo.png";
import procreateIcon from "./procreate.png";
import puppeteerIcon from "./puppeteer.png";
import reactIcon from "./react.png";
import routerIcon from "./router.png";
import sassIcon from "./sass.png";
import sketchIcon from "./sketch.png";
import storybookIcon from "./storybook.png";
import tailwindIcon from "./tailwind.png";
import towerIcon from "./tower.png";
import tsIcon from "./ts.png";
import vercelIcon from "./vercel.png";
import viteIcon from "./vite.png";
import vitestIcon from "./vitest.png";

export const alacritty = [alacrittyIcon, "Alacritty"] as const;
export const astro = [astroIcon, "Astro"] as const;
export const backlog = [backlogIcon, "Backlog"] as const;
export const bitbucket = [bitbucketIcon, "Bitbucket"] as const;
export const cc = [ccIcon, "CC"] as const;
export const css = [cssIcon, "CSS"] as const;
export const designer = [designerIcon, "Designer"] as const;
export const directus = [directusIcon, "Directus"] as const;
export const docker = [dockerIcon, "Docker"] as const;
export const figma = [figmaIcon, "Figma"] as const;
export const fish = [fishIcon, "Fish"] as const;
export const git = [gitIcon, "Git"] as const;
export const github = [githubIcon, "GitHub"] as const;
export const gitlab = [gitlabIcon, "GitLab"] as const;
export const hay = [hayIcon, "Hay"] as const;
export const hay2 = [hay2Icon, "Hay2"] as const;
export const html = [htmlIcon, "HTML"] as const;
export const jest = [jestIcon, "Jest"] as const;
export const js = [jsIcon, "JavaScript"] as const;
export const netlify = [netlifyIcon, "Netlify"] as const;
export const next = [nextIcon, "Next.js"] as const;
export const notebook = [notebookIcon, "Notebook"] as const;
export const photo = [photoIcon, "Photo"] as const;
export const procreate = [procreateIcon, "Procreate"] as const;
export const puppeteer = [puppeteerIcon, "Puppeteer"] as const;
export const react = [reactIcon, "React"] as const;
export const router = [routerIcon, "Router"] as const;
export const sass = [sassIcon, "Sass"] as const;
export const sketch = [sketchIcon, "Sketch"] as const;
export const storybook = [storybookIcon, "Storybook"] as const;
export const tailwind = [tailwindIcon, "Tailwind"] as const;
export const tower = [towerIcon, "Tower"] as const;
export const ts = [tsIcon, "TypeScript"] as const;
export const vercel = [vercelIcon, "Vercel"] as const;
export const vite = [viteIcon, "Vite"] as const;
export const vitest = [vitestIcon, "Vitest"] as const;
