name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.pnpm
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/depeche:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Login to Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            # Stop and remove existing containers
            docker rm -f depeche depeche-traefik || true
            
            # Pull latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/depeche:latest
            
            # Start services with docker-compose
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} docker-compose -f /home/${{ secrets.VPS_USERNAME }}/apps/depeche/current/docker-compose.yml up -d
