name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.pnpm
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/the-pale:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.VPS_USERNAME }}/apps/the-pale/current"
            mkdir -p $DEPLOY_PATH
            
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3.raw" \
                 -o $DEPLOY_PATH/docker-compose.yml \
                 https://api.github.com/repos/${{ github.repository }}/contents/docker-compose.yml
            
            # Login to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Stop and remove existing containers
            docker rm -f the-pale || true
            
            # Start services with docker-compose
            GITHUB_OWNER=${{ github.repository_owner }} docker compose -f $DEPLOY_PATH/docker-compose.yml up -d
